// src/components/floating-hearts/floating-hearts.component.ts
import { Component, Renderer2 } from '@angular/core';

@Component({
  selector: 'app-floating-hearts',
  standalone: true,
  imports: [],
  templateUrl: './floating-hearts.component.html',
  styleUrl: './floating-hearts.component.scss'
})
export class FloatingHeartsComponent {
  constructor(private renderer: Renderer2) { }

  ngOnInit(): void {
    setInterval(() => {
      this.createHeart();
    }, 800);
  }

  createHeart() {
    const container = document.querySelector('.hearts-container');
    if (!container) return;

    const heart = this.renderer.createElement('div');
    this.renderer.addClass(heart, 'heart');

    // Random position + animation duration
    (heart as HTMLElement).style.left = Math.random() * window.innerWidth + 'px';
    (heart as HTMLElement).style.animationDuration = (3 + Math.random() * 5) + 's';

    this.renderer.appendChild(container, heart);

    // Remove sau khi animation xong
    setTimeout(() => {
      this.renderer.removeChild(container, heart);
    }, 8000);
  }
}

// src/components/common/FloatingHearts.tsx
import { useEffect } from "react";

const FloatingHearts = () => {
   useEffect(() => {
      const createHeart = () => {
         const heart = document.createElement('div');
         heart.classList.add('heart');
         const maxWidth = window.innerWidth - 50;
         const minWidth = 50;
         const leftPosition = Math.random() * (maxWidth - minWidth) + minWidth;
         const bottomPosition = Math.random() * window.innerHeight * 0.8;
         heart.style.left = leftPosition + 'px';
         heart.style.bottom = bottomPosition + 'px';
         heart.style.animationDuration = Math.random() * 5 + 5 + 's';
         document.body.appendChild(heart);
         setTimeout(() => {
            heart.remove();
         }, 10000);
      }

      const interval = setInterval(createHeart, 500);
      return () => clearInterval(interval);
   }, []);

   return null;
}

export default FloatingHearts;
